export default {
	ADD_VALUE_SERIES: "ADD_VALUE_SERIES",
	DELETE_VALUE_SERIES: "DELETE_VALUE_SERIES",
	SAVE_VALUE_SERIES: "SAVE_VALUE_SERIES",
	UPDATE_VALUE_SERIES: "UPDATE_VALUE_SERIES",
	ADD_CATEGORY: "ADD_CATEGORY",
	DELETE_CATEGORY: "DELETE_CATEGORY",
	SAVE_CATEGORY: "SAVE_CATEGORY",
	LOADCOLLECTION_VALUE_SERIES: "LOADCOLLECTION_VALUE_SERIES"
};